apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production
nameSuffix: -production

resources:
  - ../../base

images:
  - name: bot

labels:
  - includeSelectors: true
    pairs:
      environment: production
