apiVersion: apps/v1
kind: Deployment
metadata:
  name: oddlaws-bot
spec:
  selector:
    matchLabels:
      app: oddlaws-bot
  template:
    metadata:
      labels:
        app: oddlaws-bot
    spec:
      containers:
        - name: oddlaws-bot
          image: bot
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: oddlaws-bot-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: oddlaws-db
                  key: uri
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: oddlaws-discord
                  key: token
            - name: SCREENSHOTS_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: oddlaws-bot-config
                  key: screenshots-channel-id
            - name: PUBLISHED_MEMBER_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: oddlaws-bot-config
                  key: published-member-role-id
            - name: OBLIVION_SOCIAL_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: oddlaws-bot-config
                  key: oblivion-social-channel-id
            - name: OBLIVION_SOCIAL_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: oddlaws-bot-config
                  key: oblivion-social-role-id
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
