apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging
nameSuffix: -staging

resources:
  - ../../base

images:
  - name: bot

labels:
  - includeSelectors: true
    pairs:
      environment: staging
